# Generated by Django 4.2.3 on 2023-07-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicaciones.categoria')),
                ('subNombre', models.CharField(max_length=80)),
            ],
            bases=('publicaciones.categoria',),
        ),
    ]
