# Generated by Django 4.2.3 on 2023-07-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_subcategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
